name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # RHEL 9 does not have GitHub Actions support, so we use Ubuntu as a runner

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz

    - name: Extract ngrok
      run: tar -xzvf ngrok-v3-stable-linux-arm64.tgz && pwd

    - name: Auth
      run: ~\ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ngrok http --domain=rattler-coherent-deadly.ngrok-free.app 80
