name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.tgz && pwd

    - name: Extract ngrok
      run: tar -xzvf ngrok-v3-stable-linux-386.tgz

    - name: Auth
      run: /home/runner/work/Ubantu/Ubantu/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: /home/runner/work/Ubantu/Ubantu/ngrok http --domain=rattler-coherent-deadly.ngrok-free.app 80
