name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-386.tgz
        tar -xzvf ngrok-v3-stable-linux-386.tgz

    - name: Auth
      run: /home/runner/work/Ubantu/Ubantu/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Apache
      run: |
        php -v
        sudo apt-get update
        AddType application/x-httpd-php .php
        sudo apt-get install -y apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2

    - name: Delete Old Data from Apache Folder
      run: |
        sudo rm -rf /var/www/html/*

    - name: Download and Extract
      run: |
        wget -O TS-JioTV.zip "https://tsnehcors.mitthu.workers.dev/?https://github.com/mitthu786/TS-JioTV/blob/main/TS-JioTV.zip?raw=true"
        unzip TS-JioTV.zip -d extracted_folder

    - name: Move Contents to Apache Folder
      run: |
        sudo mv extracted_folder/* /var/www/html/
        sudo chown -R www-data:www-data /var/www/html

    - name: Create Tunnel
      run: /home/runner/work/Ubantu/Ubantu/ngrok http ${{ secrets.NGROK_TUNNEL_COMMAND }} 80
