name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Timeout after 60 minutes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: echo "Building..."
