name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # RHEL 9 does not have GitHub Actions support, so we use Ubuntu as a runner

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: |
        sudo yum install -y xrdp
        sudo systemctl start xrdp
        sudo systemctl enable xrdp

    - name: Set Password
      run: sudo passwd runneradmin
      # You may need to interactively set the password here

    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
