name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # RHEL 9 does not have GitHub Actions support, so we use Ubuntu as a runner

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz

    - name: Extract ngrok
      run: tar -xzvf ngrok-v3-stable-linux-arm64.tgz

    - name: Auth
      run: ./ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: |
        sudo apt install -y xrdp
        sudo systemctl start xrdp
        sudo systemctl enable xrdp

    - name: Set Password
      run: sudo passwd runneradmin
      # You may need to interactively set the password here

    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
